version: 2
jobs:
  build:
    docker:
      - image: xd009642/tarpaulin
    steps:
      - checkout
      - run: rustup toolchain install stable
      - run: cargo +stable build
      - run: cargo +stable test --all-targets
      - run: cargo build
      - run: cargo clippy
      - run: cargo tarpaulin --all-targets --out Xml
      - run:
          name: Uploading code coverage
          command: |
              bash <(curl -s https://codecov.io/bash)
